#!/usr/bin/env python3
"""Generate the Android launcher icon resources from assets/favicon.svg.

The brand icon single source is assets/favicon.svg (root CLAUDE.md). This
script converts its <rect> background and <path> glyph into the two Android
resource files the adaptive icon references, so the APK icon can never drift
from the web icon. Output files are gitignored; CI runs this before gradle.

The favicon glyph is drawn in a 512 viewBox and mapped into the 24 canvas by
its nested transform (translate(12 12) scale(0.016) translate(-512 -512)) —
carried over verbatim as nested <group>s (VectorDrawable has no transform
attribute, so the right-to-left SVG transforms become outside-in groups).
On the 24 canvas the glyph spans x[8.85,14.93] y[7.87,18.45] (center
11.9,13.2, width 6.08). The outer group scales it 6x and translates the
center to the 108dp canvas center (54,54):
    translateX = 54 - 11.9*6   = -17.4
    translateY = 54 - 13.2*6   = -25.2
The glyph then spans x[35.7,72.2] y[22,85.5] — fully inside the
adaptive-icon safe zone (diameter-66 center circle), 36.5dp wide (~55% of
the zone, slightly larger than the favicon's 25% so it reads on a launcher).

Usage: python .github/scripts/sync-android-icon.py   (repo root)
"""

import re
import sys
from pathlib import Path
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parent.parent.parent
SRC = ROOT / "assets" / "favicon.svg"
FG_OUT = ROOT / "frontend" / "android" / "app" / "src" / "main" / "res" / "drawable" / "ic_launcher_foreground.xml"
BG_OUT = ROOT / "frontend" / "android" / "app" / "src" / "main" / "res" / "values" / "ic_launcher_background.xml"

# Outer adaptive transform: scale 6x, translate glyph center (11.9,13.2) to (54,54).
ADAPTIVE_SCALE = 6.0
ADAPTIVE_TX = 54.0 - 11.9 * ADAPTIVE_SCALE
ADAPTIVE_TY = 54.0 - 13.2 * ADAPTIVE_SCALE

NS = {"svg": "http://www.w3.org/2000/svg"}


def transform_groups(transform, indent="        "):
    """Turn an SVG transform string into nested VectorDrawable <group>s.

    SVG applies transforms right-to-left; VectorDrawable groups apply
    outside-in, so the rightmost transform becomes the innermost group.
    """
    ops = re.findall(r"(translate|scale)\(([^)]*)\)", transform)
    body = ""
    for op, args in reversed(ops):  # rightmost op first → innermost group
        vals = [float(v) for v in args.replace(",", " ").split()]
        attrs = []
        if op == "translate":
            attrs.append(f"android:translateX=\"{vals[0]}\"")
            attrs.append(f"android:translateY=\"{vals[1] if len(vals) > 1 else 0.0}\"")
        else:  # scale
            sx = vals[0]
            sy = vals[1] if len(vals) > 1 else sx
            attrs.append(f"android:scaleX=\"{sx}\"")
            attrs.append(f"android:scaleY=\"{sy}\"")
        inner = f"\n{indent}    ".join(attrs)
        body = f"<group {inner}>\n{body}\n{indent}</group>"
    return body


def main():
    tree = ET.parse(SRC)
    root = tree.getroot()
    rect = root.find("svg:rect", NS)
    glyph_container = root.find(".//svg:g", NS)
    glyph = glyph_container.find("svg:path", NS) if glyph_container is not None else None
    if rect is None or glyph is None:
        sys.exit("favicon.svg must contain a <rect> background and one <path> glyph")
    bg_color = rect.get("fill") or sys.exit("favicon <rect> has no fill")
    path_data = glyph.get("d") or sys.exit("favicon <path> has no d")
    glyph_fill = glyph.get("fill") or "#FFFFFF"
    # The transform lives on the <g>, not the <path> — carry it over so the
    # 512-coordinate glyph maps into the 24 canvas exactly like the favicon.
    glyph_transform = transform_groups(glyph_container.get("transform") or "")

    fg = f"""<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by .github/scripts/sync-android-icon.py from assets/favicon.svg — do not edit.
     The glyph (with its original favicon transform) is scaled {ADAPTIVE_SCALE:g}x
     and translated to the 108dp canvas center (54,54), fully inside the
     adaptive-icon safe zone. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <group
        android:scaleX="{ADAPTIVE_SCALE:g}"
        android:scaleY="{ADAPTIVE_SCALE:g}"
        android:translateX="{ADAPTIVE_TX:g}"
        android:translateY="{ADAPTIVE_TY:g}">
{glyph_transform}
        <path
            android:fillColor="{glyph_fill}"
            android:pathData="{path_data}" />
    </group>
</vector>
"""
    bg = f"""<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by .github/scripts/sync-android-icon.py from assets/favicon.svg — do not edit. -->
<resources>
    <color name="ic_launcher_background">{bg_color.upper()}</color>
</resources>
"""
    FG_OUT.write_text(fg, encoding="utf-8")
    BG_OUT.write_text(bg, encoding="utf-8")
    print(f"wrote {FG_OUT.relative_to(ROOT)}")
    print(f"wrote {BG_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
